# Generated by Django 5.1.1 on 2024-09-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_product_cart_products_watcheupload_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='watchreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='WatchReview',
        ),
    ]
