# Generated by Django 5.1.1 on 2024-09-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_watchreview_product_remove_watchreview_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watcheupload',
            name='count',
        ),
    ]
