# Generated by Django 5.1.1 on 2024-09-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_watcheupload_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatcheUpload',
            new_name='WatchUpload',
        ),
    ]
