# Generated by Django 5.1.1 on 2024-10-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_watchreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='homepage.watchupload'),
        ),
    ]
