# Generated by Django 5.1.1 on 2024-09-24 13:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_rename_watcheupload_watchupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Carts',
        ),
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Wishlists',
        ),
    ]
