# Generated by Django 5.1.1 on 2024-10-23 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchreview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchreview',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
