# Generated by Django 5.1.1 on 2024-10-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_watchreview_created_watchreview_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='watchupload',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
