# Generated by Django 5.1.1 on 2024-09-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_rename_cart_carts_rename_wishlist_wishlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlists',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlists',
            name='user',
        ),
        migrations.DeleteModel(
            name='Carts',
        ),
        migrations.DeleteModel(
            name='Wishlists',
        ),
    ]
