# Generated by Django 5.1.1 on 2024-09-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_remove_wishlists_product_remove_wishlists_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchUpload',
            new_name='WatcheUpload',
        ),
    ]
